# Generated by Django 5.1.7 on 2025-05-08 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concurrent_modification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helptickets',
            name='ticket_title',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='helptickets',
            name='ticket_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='concurrent_modification.users'),
        ),
    ]
