# Generated by Django 5.1.7 on 2025-05-08 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concurrent_modification', '0002_helptickets_ticket_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helptickets',
            name='ticket_title',
        ),
        migrations.AlterField(
            model_name='helptickets',
            name='ticket_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='concurrent_modification.users'),
        ),
    ]
